disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Machine Learning for Molecule Simulations and Sampling"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Welcome to the Machine Learning for Simulations Reading Group, hosted by the University of Cambridge Computational Biology Laboratory. We are an international academic community dedicated to the exploration and advancement of machine learning methodologies, specifically focusing on sampling techniques such as Markov Chain Monte Carlo (MCMC) and neural samplers, including Boltzmann generators. Our mission is to foster intellectual exchange, collaborative learning, and groundbreaking research in the application of these methods to molecular dynamics and molecule generation."
