[[main]]
name = "About"
pageRef = "About"
weight = 1

[[main]]
name = "People"
pageRef = "People"
weight = 3

[[main]]
name = "Recording"
pageRef = "Recording"
weight = 4

[[main]]
name = "Schedule"
pageRef = "Schedule"
weight = 2

[[main]]
pageRef = "no"
identifier = "eDHspjsFaU"
weight = 9999

